/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.*;
import javax.swing.*;
import Process.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NGUYENIT
 */
public class JfrmDangky extends javax.swing.JFrame {

    /**
     * Creates new form jfmDangky
     */
    public JfrmDangky() throws UnsupportedLookAndFeelException {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JfrmDangky.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(JfrmDangky.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JfrmDangky.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }
    private static ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_xacnhandangky = new javax.swing.JButton();
        txt_tentaikhoan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_matkhau = new javax.swing.JPasswordField();
        btn_thoat = new javax.swing.JButton();
        btn_nhaplai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_matkhau1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐĂNG KÝ TÀI KHOẢN");

        jLabel1.setText("Tên tài khoản:");

        btn_xacnhandangky.setText("Đăng ký");
        btn_xacnhandangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacnhandangkyActionPerformed(evt);
            }
        });

        jLabel2.setText("Mật khẩu:");

        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        btn_nhaplai.setText("Nhập lại");
        btn_nhaplai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhaplaiActionPerformed(evt);
            }
        });

        jLabel3.setText("Xác nhận mật khẩu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(btn_xacnhandangky)
                .addGap(47, 47, 47)
                .addComponent(btn_nhaplai)
                .addGap(51, 51, 51)
                .addComponent(btn_thoat)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_matkhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tentaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tentaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_matkhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xacnhandangky)
                    .addComponent(btn_thoat)
                    .addComponent(btn_nhaplai))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xacnhandangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacnhandangkyActionPerformed
        // TODO add your handling code here:
        if (this.txt_tentaikhoan.getText().length() == 0 || String.valueOf(this.txt_matkhau.getPassword()).length() == 0 || String.valueOf(this.txt_matkhau1.getPassword()).length() == 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đầy đủ thông tin về tên tài khoản hoặc mật khẩu", "Thông báo", 1);

        } else if (this.txt_tentaikhoan.getText().length() > 30) {
            JOptionPane.showMessageDialog(null, "Tên tài khoản không được quá 30 ký tự", "Thông báo", 1);
        } else if (String.valueOf(this.txt_matkhau.getPassword()).length() > 20) {
            JOptionPane.showMessageDialog(null, "Mật khẩu không được quá 20 ký tự", "Thông báo", 1);
        } else if (String.valueOf(this.txt_matkhau.getPassword()).equals(String.valueOf(this.txt_matkhau1.getPassword())) == false) {
            JOptionPane.showMessageDialog(null, "Mật khẩu xác nhận không trùng với mật khẩu đăng ký, mời nhập lại", "Thông báo", 1);
            txt_matkhau1.setText(null);
        } else {
            rs = Kiemtra_Taikhoan.kiemtraDangky(this.txt_tentaikhoan.getText());
            try {
                if (rs.next()) {
                    //Tên tài khoản đã tồn tại
                    JOptionPane.showMessageDialog(null, "Tên tài khoản " + '"' + this.txt_tentaikhoan.getText() + '"' + " đã tồn tại, đề nghị đổi tên khác", "Thông báo", 1);
                } else {
                    //Đăng nhập thành công
                    User.InsertUser(this.txt_tentaikhoan.getText().trim(), String.valueOf(this.txt_matkhau.getPassword()));
                    new JfrmDangnhap().setVisible(true);
                    this.dispose();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Thông báo", 1);
            }

        }
    }//GEN-LAST:event_btn_xacnhandangkyActionPerformed

    private void btn_nhaplaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhaplaiActionPerformed
        // TODO add your handling code here:
        this.txt_tentaikhoan.setText(null);
        this.txt_matkhau.setText(null);
        this.txt_matkhau1.setText(null);
    }//GEN-LAST:event_btn_nhaplaiActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thoát hay không?", "Thông báo", 2) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JfrmDangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JfrmDangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JfrmDangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JfrmDangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JfrmDangky().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(JfrmDangky.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nhaplai;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xacnhandangky;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txt_matkhau;
    private javax.swing.JPasswordField txt_matkhau1;
    private javax.swing.JTextField txt_tentaikhoan;
    // End of variables declaration//GEN-END:variables
}
