/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Model.BangDiemModel;
import Model.MonHocModel;
import Process.BangDiem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author lenovo g4070
 */
public class ThemMoiBangDiemForm extends javax.swing.JFrame {

    /**
     * Creates new form ThemMoiBangDiemForm
     */
    private final JfrmMain jfrmMain;
    ArrayList<MonHocModel> lstcbbmonhoc = new ArrayList<MonHocModel>();
    public BangDiemModel BangDiemEdit = new BangDiemModel();
    BangDiem progess = new BangDiem();
    Float diemtongket = 0.0f;
    public ThemMoiBangDiemForm(JfrmMain home) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThemMoiBangDiemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ThemMoiBangDiemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ThemMoiBangDiemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ThemMoiBangDiemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jfrmMain = home;
        initComponents();
    }

    public ThemMoiBangDiemForm(JfrmMain home, String masinhvien, String tensinhvien) {
        this.jfrmMain = home;
        initComponents();
        txt_bd_masinhvienadd.setText(masinhvien);
        BangDiemEdit.setMasinhvien(masinhvien);
        txt_bd_tensinhvienadd.setText(tensinhvien);
        BangDiemEdit.setTensinhvien(tensinhvien);
        getcbbmonhoc();
        for (MonHocModel item : lstcbbmonhoc) {
            cbb_bd_TenMonHocAdd.addItem(item.getTenmonhoc());
            cbb_bd_MaMonHocAdd.addItem(item.getId_mon());
        }
        cbb_bd_TenMonHocAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                cbb_bd_TenMonHocAdd.getSelectedItem().toString();
                for(MonHocModel item : lstcbbmonhoc){
                    if (cbb_bd_TenMonHocAdd.getSelectedItem().toString().equals(item.getTenmonhoc())){
                        cbb_bd_MaMonHocAdd.setSelectedItem(item.getId_mon());
                    }
                }
            }
        });
        cbb_bd_MaMonHocAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                cbb_bd_MaMonHocAdd.getSelectedItem().toString();
                for(MonHocModel item : lstcbbmonhoc){
                    if (cbb_bd_MaMonHocAdd.getSelectedItem().toString().equals(item.getId_mon())){
                        cbb_bd_TenMonHocAdd.setSelectedItem(item.getTenmonhoc());
                    }
                }
            }
        });
        
    }

    public void getcbbmonhoc() {
        try {
            lstcbbmonhoc = progess.cbbmonhoc();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThemMoiBangDiemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ThemMoiBangDiemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txt_bd_diemkiemtra2add = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_bd_ThemMoiBangDiemadd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_bd_diemthicuoikiadd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_bd_TinhDiemTKBangDiemadd = new javax.swing.JButton();
        txt_bd_masinhvienadd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_bd_Xeploaiadd = new javax.swing.JTextField();
        txt_bd_diemkiemtra1add = new javax.swing.JTextField();
        txt_bd_diemtongketadd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_bd_tensinhvienadd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbb_bd_MaMonHocAdd = new javax.swing.JComboBox<>();
        cbb_bd_TenMonHocAdd = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THÊM MỚI BẢNG ĐIỂM");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Mã Môn Học:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Tên Môn Học:");

        btn_bd_ThemMoiBangDiemadd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_bd_ThemMoiBangDiemadd.setText("Thêm Mới");
        btn_bd_ThemMoiBangDiemadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bd_ThemMoiBangDiemaddActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Điểm kiểm tra 1:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Điểm thi cuối kì:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Điểm kiểm tra 2:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Điểm tổng kết:");

        btn_bd_TinhDiemTKBangDiemadd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_bd_TinhDiemTKBangDiemadd.setLabel("TÍNH ĐIỂM TỔNG KẾT");
        btn_bd_TinhDiemTKBangDiemadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bd_TinhDiemTKBangDiemaddActionPerformed(evt);
            }
        });

        txt_bd_masinhvienadd.setEditable(false);
        txt_bd_masinhvienadd.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        txt_bd_masinhvienadd.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Xếp loại:");

        txt_bd_Xeploaiadd.setEditable(false);
        txt_bd_Xeploaiadd.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        txt_bd_Xeploaiadd.setEnabled(false);

        txt_bd_diemtongketadd.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        txt_bd_diemtongketadd.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Mã Sinh Viên:");

        txt_bd_tensinhvienadd.setEditable(false);
        txt_bd_tensinhvienadd.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        txt_bd_tensinhvienadd.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Tên Sinh Viên:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbb_bd_TenMonHocAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbb_bd_MaMonHocAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_bd_masinhvienadd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel7))
                                    .addGap(8, 8, 8))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_bd_tensinhvienadd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_bd_diemthicuoikiadd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bd_diemkiemtra1add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bd_diemkiemtra2add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_bd_diemtongketadd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bd_Xeploaiadd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_bd_ThemMoiBangDiemadd)
                        .addGap(41, 41, 41))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_bd_TinhDiemTKBangDiemadd)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_bd_masinhvienadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_bd_tensinhvienadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbb_bd_MaMonHocAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_bd_diemkiemtra1add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_bd_diemkiemtra2add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbb_bd_TenMonHocAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bd_diemthicuoikiadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btn_bd_TinhDiemTKBangDiemadd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bd_diemtongketadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_bd_ThemMoiBangDiemadd, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_bd_Xeploaiadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bd_ThemMoiBangDiemaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bd_ThemMoiBangDiemaddActionPerformed
        boolean checkforupdate = true;
        // Lấy mã môn học
        for(MonHocModel item : lstcbbmonhoc){
                    if (cbb_bd_MaMonHocAdd.getSelectedItem().toString().equals(item.getId_mon())){
                        BangDiemEdit.setMamonhoc(item.getMamonhoc());
                    }
                }
        //
        try {
            if (txt_bd_diemkiemtra1add.getText().equals("")) {
                BangDiemEdit.setDiemkiemtra_1(-1f);
            } else {
                BangDiemEdit.setDiemkiemtra_1(Float.parseFloat(txt_bd_diemkiemtra1add.getText()));
                if (BangDiemEdit.getDiemkiemtra_1() >10 || BangDiemEdit.getDiemkiemtra_1()<0){
                    checkforupdate = false;
                }
            }
        } catch (Exception ex) {
            checkforupdate = false;
           
        }

        try {
            if (txt_bd_diemkiemtra2add.getText().equals("")) {
                BangDiemEdit.setDiemkiemtra_2(-1f);
            } else {
                BangDiemEdit.setDiemkiemtra_2(Float.parseFloat(txt_bd_diemkiemtra2add.getText()));
                if (BangDiemEdit.getDiemkiemtra_2()>10 || BangDiemEdit.getDiemkiemtra_2()<0){
                    checkforupdate = false;
                }
            }
        } catch (Exception ex) {
            checkforupdate = false;
            
        }
        try {
            if (txt_bd_diemthicuoikiadd.getText().equals("")) {
                BangDiemEdit.setDiemthicuoiky(-1f);
            } else {
                BangDiemEdit.setDiemthicuoiky(Float.parseFloat(txt_bd_diemthicuoikiadd.getText()));
                if (BangDiemEdit.getDiemthicuoiky()>10 || BangDiemEdit.getDiemthicuoiky()<0){
                    checkforupdate = false;
                }
            }

        } catch (Exception ex) {
            checkforupdate = false;
            //JOptionPane.showMessageDialog(null, "Vui lòng nhập số cho các trường !", "Vui lòng nhập số cho các trường !", JOptionPane.ERROR_MESSAGE);
        }
        if (BangDiemEdit.getDiemkiemtra_1() == -1f || BangDiemEdit.getDiemkiemtra_2() == -1f || BangDiemEdit.getDiemthicuoiky() == -1f) {
            BangDiemEdit.setDiemtongket(-1f);
        } else {
            BangDiemEdit.setDiemtongket((BangDiemEdit.getDiemkiemtra_1() + BangDiemEdit.getDiemkiemtra_2() + BangDiemEdit.getDiemthicuoiky() * 2) / 4);
        }
        BangDiemEdit.setXeploai(checkxeploai(BangDiemEdit.getDiemtongket()));
        if(checkforupdate){
            try {
            progess.AddBangDiem(BangDiemEdit);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ChiTietCapNhatBangDiemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ChiTietCapNhatBangDiemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        this.jfrmMain.setVisible(true);
        this.jfrmMain.fillDataBangDiem2Table();
        }
        else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập giá trị điểm từ 0 đến 10 !", "Vui lòng nhập giá trị điểm từ 0 đến 10 !", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_bd_ThemMoiBangDiemaddActionPerformed

    private void btn_bd_TinhDiemTKBangDiemaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bd_TinhDiemTKBangDiemaddActionPerformed
        try {
            diemtongket = (Float.parseFloat(txt_bd_diemkiemtra1add.getText()) + Float.parseFloat(txt_bd_diemkiemtra2add.getText()) + Float.parseFloat(txt_bd_diemthicuoikiadd.getText()) * 2) / 4;
            txt_bd_diemtongketadd.setText(String.valueOf(diemtongket));
        } catch (Exception ex) {
            diemtongket = -1f;
            txt_bd_diemtongketadd.setText("None");
        }
        txt_bd_Xeploaiadd.setText(checkxeploai(diemtongket));
    }//GEN-LAST:event_btn_bd_TinhDiemTKBangDiemaddActionPerformed
    
    public String checkxeploai(float diem) {
        String xeploai = "";
        if (diem >= 8) {
            xeploai = "Distinction";
        }
        if (diem < 8 && diem >= 6) {
            xeploai = "Credit";
        }
        if (diem < 6 && diem >= 4) {
            xeploai = "Pass";
        }
        if (diem >= 0 && diem < 4) {
            xeploai = "Fail";
        }
        if (diem < 0) {
            xeploai = "None";
        }
        return xeploai;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemMoiBangDiemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemMoiBangDiemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemMoiBangDiemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemMoiBangDiemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ThemMoiBangDiemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bd_ThemMoiBangDiemadd;
    private javax.swing.JButton btn_bd_TinhDiemTKBangDiemadd;
    private javax.swing.JComboBox<String> cbb_bd_MaMonHocAdd;
    private javax.swing.JComboBox<String> cbb_bd_TenMonHocAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_bd_Xeploaiadd;
    private javax.swing.JTextField txt_bd_diemkiemtra1add;
    private javax.swing.JTextField txt_bd_diemkiemtra2add;
    private javax.swing.JTextField txt_bd_diemthicuoikiadd;
    private javax.swing.JTextField txt_bd_diemtongketadd;
    private javax.swing.JTextField txt_bd_masinhvienadd;
    private javax.swing.JTextField txt_bd_tensinhvienadd;
    // End of variables declaration//GEN-END:variables
}
